package ffmpeg

import (
	"strings"
	"testing"
)

func TestParseCube(t *testing.T) {
	valid2x2 := `# Test LUT generated by Gocut tests
TITLE "Test 2x2x2"
LUT_3D_SIZE 2
DOMAIN_MIN 0.0 0.0 0.0
DOMAIN_MAX 1.0 1.0 1.0
0.0 0.0 0.0
0.0 0.0 1.0
0.0 1.0 0.0
0.0 1.0 1.0
1.0 0.0 0.0
1.0 0.0 1.0
1.0 1.0 0.0
1.0 1.0 1.0
`

	tests := []struct {
		name      string
		input     string
		wantErr   string // substring expected in the error; empty means success
		wantSize  int
		wantTitle string
		wantFirst []float32
		wantLast  []float32
	}{
		{
			name:      "valid 2x2x2 cube",
			input:     valid2x2,
			wantSize:  2,
			wantTitle: "Test 2x2x2",
			wantFirst: []float32{0, 0, 0},
			wantLast:  []float32{1, 1, 1},
		},
		{
			name: "comments and title tolerated",
			input: `# leading comment
TITLE "Funky / Look #1"
# another comment
LUT_3D_SIZE 2
# comment inside the table
0 0 0  0 0 1
0 1 0  0 1 1
1 0 0
# trailing comment
1 0 1  1 1 0  1 1 1
`,
			wantSize:  2,
			wantTitle: "Funky / Look #1",
			wantFirst: []float32{0, 0, 0},
			wantLast:  []float32{1, 1, 1},
		},
		{
			name: "missing size",
			input: `TITLE "No size"
0.0 0.0 0.0
1.0 1.0 1.0
`,
			wantErr: "table data found before LUT_3D_SIZE",
		},
		{
			name: "missing size header only",
			input: `TITLE "No size at all"
`,
			wantErr: "missing LUT_3D_SIZE",
		},
		{
			name: "wrong entry count",
			input: `LUT_3D_SIZE 2
0.0 0.0 0.0
0.0 0.0 1.0
`,
			wantErr: "expected 8 LUT entries (2^3 RGB triplets), found 2",
		},
		{
			name: "out of range value",
			input: `LUT_3D_SIZE 2
0.0 0.0 0.0
0.0 0.0 1.5
0.0 1.0 0.0
0.0 1.0 1.0
1.0 0.0 0.0
1.0 0.0 1.0
1.0 1.0 0.0
1.0 1.0 1.0
`,
			wantErr: "line 3: LUT value 1.5 out of range (0..1)",
		},
		{
			name: "1D lut rejected",
			input: `LUT_1D_SIZE 256
0.0 0.0 0.0
`,
			wantErr: "only 3D LUTs are supported",
		},
		{
			name: "size out of bounds",
			input: `LUT_3D_SIZE 512
`,
			wantErr: "LUT_3D_SIZE 512 out of range (2..256)",
		},
		{
			name: "windows line endings",
			input: "TITLE \"CRLF\"\r\nLUT_3D_SIZE 2\r\n" +
				"0 0 0\r\n0 0 1\r\n0 1 0\r\n0 1 1\r\n1 0 0\r\n1 0 1\r\n1 1 0\r\n1 1 1\r\n",
			wantSize:  2,
			wantTitle: "CRLF",
			wantFirst: []float32{0, 0, 0},
			wantLast:  []float32{1, 1, 1},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			lut, err := ParseCube([]byte(tt.input))
			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("expected error containing %q, got nil", tt.wantErr)
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("error %q does not contain %q", err.Error(), tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if lut.Size != tt.wantSize {
				t.Errorf("Size = %d, want %d", lut.Size, tt.wantSize)
			}
			if lut.Title != tt.wantTitle {
				t.Errorf("Title = %q, want %q", lut.Title, tt.wantTitle)
			}
			wantLen := 3 * tt.wantSize * tt.wantSize * tt.wantSize
			if len(lut.Table) != wantLen {
				t.Fatalf("len(Table) = %d, want %d", len(lut.Table), wantLen)
			}
			for j, v := range tt.wantFirst {
				if lut.Table[j] != v {
					t.Errorf("Table[%d] = %v, want %v", j, lut.Table[j], v)
				}
			}
			for j, v := range tt.wantLast {
				if lut.Table[len(lut.Table)-3+j] != v {
					t.Errorf("Table[last-%d] = %v, want %v", 3-1-j, lut.Table[len(lut.Table)-3+j], v)
				}
			}
		})
	}
}

func TestParseCubeFileMissing(t *testing.T) {
	if _, err := ParseCubeFile("does-not-exist.cube"); err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}
