// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function CancelRender(arg1:string):Promise<void>;

export function CheckFFmpegInstalled():Promise<string>;

export function ClearPreviewCache():Promise<void>;

export function ClearRecentProjects():Promise<void>;

export function Close():Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportProjectFile(arg1:project.Project):Promise<string>;

export function ExtractThumbnail(arg1:string,arg2:number):Promise<string>;

export function ExtractWaveform(arg1:string):Promise<Array<number>>;

export function GenerateThumbnailStrip(arg1:string,arg2:number):Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetMediaInfo(arg1:string):Promise<project.MediaInfo>;

export function GetMediaServerPort():Promise<number>;

export function GetPreviewFrame(arg1:project.Project,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetRecentProjects():Promise<Array<project.RecentProject>>;

export function GetRenderProgress(arg1:string):Promise<project.RenderProgress>;

export function GetRenderQueue():Promise<Array<project.RenderProgress>>;

export function ImportMedia(arg1:Array<string>):Promise<Array<project.Asset>>;

export function LoadProject(arg1:string):Promise<project.Project>;

export function Maximise():Promise<void>;

export function Minimise():Promise<void>;

export function NewProject(arg1:project.ProjectSettings):Promise<project.Project>;

export function OpenDirectoryPicker():Promise<string>;

export function OpenFilePicker(arg1:Array<project.FileFilter>):Promise<Array<string>>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function PreloadFrames(arg1:project.Project,arg2:number,arg3:number):Promise<void>;

export function SaveFilePicker(arg1:string,arg2:Array<project.FileFilter>):Promise<string>;

export function SaveProject(arg1:project.Project):Promise<void>;

export function StartRender(arg1:project.Project,arg2:project.RenderSettings):Promise<string>;
