// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeMotion(arg1) {
  return window['go']['app']['App']['AnalyzeMotion'](arg1);
}

export function ApplyStabilization(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyStabilization'](arg1, arg2, arg3);
}

export function CancelRender(arg1) {
  return window['go']['app']['App']['CancelRender'](arg1);
}

export function CheckFFmpegInstalled() {
  return window['go']['app']['App']['CheckFFmpegInstalled']();
}

export function ClearPreviewCache() {
  return window['go']['app']['App']['ClearPreviewCache']();
}

export function ClearRecentProjects() {
  return window['go']['app']['App']['ClearRecentProjects']();
}

export function Close() {
  return window['go']['app']['App']['Close']();
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function ExportProjectFile(arg1) {
  return window['go']['app']['App']['ExportProjectFile'](arg1);
}

export function ExtractThumbnail(arg1, arg2) {
  return window['go']['app']['App']['ExtractThumbnail'](arg1, arg2);
}

export function ExtractWaveform(arg1) {
  return window['go']['app']['App']['ExtractWaveform'](arg1);
}

export function GenerateThumbnailStrip(arg1, arg2) {
  return window['go']['app']['App']['GenerateThumbnailStrip'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetMediaInfo(arg1) {
  return window['go']['app']['App']['GetMediaInfo'](arg1);
}

export function GetMediaServerPort() {
  return window['go']['app']['App']['GetMediaServerPort']();
}

export function GetPreviewFrame(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetPreviewFrame'](arg1, arg2, arg3, arg4);
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function GetRenderProgress(arg1) {
  return window['go']['app']['App']['GetRenderProgress'](arg1);
}

export function GetRenderQueue() {
  return window['go']['app']['App']['GetRenderQueue']();
}

export function ImportMedia(arg1) {
  return window['go']['app']['App']['ImportMedia'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['app']['App']['LoadProject'](arg1);
}

export function Maximise() {
  return window['go']['app']['App']['Maximise']();
}

export function Minimise() {
  return window['go']['app']['App']['Minimise']();
}

export function NewProject(arg1) {
  return window['go']['app']['App']['NewProject'](arg1);
}

export function OpenDirectoryPicker() {
  return window['go']['app']['App']['OpenDirectoryPicker']();
}

export function OpenFilePicker(arg1) {
  return window['go']['app']['App']['OpenFilePicker'](arg1);
}

export function OpenOutputFolder(arg1) {
  return window['go']['app']['App']['OpenOutputFolder'](arg1);
}

export function PreloadFrames(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreloadFrames'](arg1, arg2, arg3);
}

export function SaveFilePicker(arg1, arg2) {
  return window['go']['app']['App']['SaveFilePicker'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['app']['App']['SaveProject'](arg1);
}

export function StartRender(arg1, arg2) {
  return window['go']['app']['App']['StartRender'](arg1, arg2);
}
