export {
  NewProject,
  SaveProject,
  LoadProject,
  GetRecentProjects,
  ExportProjectFile,
  ImportMedia,
  ExtractThumbnail,
  ExtractWaveform,
  GetMediaInfo,
  GenerateThumbnailStrip,
  StartRender,
  GetRenderProgress,
  CancelRender,
  GetRenderQueue,
  OpenOutputFolder,
  GetPreviewFrame,
  PreloadFrames,
  ClearPreviewCache,
  CheckFFmpegInstalled,
  OpenFilePicker,
  GetAppVersion,
  GetMediaServerPort,
} from '../../wailsjs/go/app/App.js'

